CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_be (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  company_rel_in_cocd STRING COMMENT 'Company Rel  in CoCd',
  o_pos_acqu_date_lot TIMESTAMP COMMENT 'O Pos Acqu Date Lot',
  securities_account STRING COMMENT 'Securities Account',
  special_fund STRING COMMENT 'Special Fund',
  in_course STRING COMMENT 'In Course',
  last_position_date TIMESTAMP COMMENT 'Last Position Date',
  position_management STRING COMMENT 'Position Management',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number',
  inc_nom_mat_lc DECIMAL(17,2) COMMENT 'Inc Nom mat  LC',
  out_nom_mat_pc DECIMAL(17,2) COMMENT 'Out Nom mat  PC',
  non_liberated_1 DECIMAL(17,2) COMMENT 'Non Liberated',
  non_liberated_2 DECIMAL(17,2) COMMENT 'Non Liberated')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_be';

CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_be_all (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  company_rel_in_cocd STRING COMMENT 'Company Rel  in CoCd',
  o_pos_acqu_date_lot TIMESTAMP COMMENT 'O Pos Acqu Date Lot',
  securities_account STRING COMMENT 'Securities Account',
  special_fund STRING COMMENT 'Special Fund',
  in_course STRING COMMENT 'In Course',
  last_position_date TIMESTAMP COMMENT 'Last Position Date',
  position_management STRING COMMENT 'Position Management',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number',
  inc_nom_mat_lc DECIMAL(17,2) COMMENT 'Inc Nom mat  LC',
  out_nom_mat_pc DECIMAL(17,2) COMMENT 'Out Nom mat  PC',
  non_liberated_1 DECIMAL(17,2) COMMENT 'Non Liberated',
  non_liberated_2 DECIMAL(17,2) COMMENT 'Non Liberated')
PARTITIONED BY (yyyy STRING, mm STRING, dd STRING, hhmmss STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_be';


CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_de (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  special_fund STRING COMMENT 'Special Fund',
  sr_product STRING COMMENT 'SR Product',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number',
  position_grouping_acc_para_4_gba_sec_and_loans STRING COMMENT 'Position grouping acc  Para 14 GBA (Sec  and loans)',
  units_harmonized_sf DECIMAL(17,3) COMMENT 'Units Harmonized(SF)',
  nominal_sf DECIMAL(17,2) COMMENT 'Nominal (SF)',
  market_value_pc_sf DECIMAL(17,2) COMMENT 'Market Value PC (SF)',
  market_value_lc_sf DECIMAL(17,2) COMMENT 'Market Value LC (SF)',
  book_value_sf DECIMAL(17,2) COMMENT 'Book Value (SF)',
  accrued_interests_sf DECIMAL(17,2) COMMENT 'Accrued Interests SF')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_de';

CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_de_all (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  special_fund STRING COMMENT 'Special Fund',
  sr_product STRING COMMENT 'SR Product',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number',
  position_grouping_acc_para_4_gba_sec_and_loans STRING COMMENT 'Position grouping acc  Para 14 GBA (Sec  and loans)',
  units_harmonized_sf DECIMAL(17,3) COMMENT 'Units Harmonized(SF)',
  nominal_sf DECIMAL(17,2) COMMENT 'Nominal (SF)',
  market_value_pc_sf DECIMAL(17,2) COMMENT 'Market Value PC (SF)',
  market_value_lc_sf DECIMAL(17,2) COMMENT 'Market Value LC (SF)',
  book_value_sf DECIMAL(17,2) COMMENT 'Book Value (SF)',
  accrued_interests_sf DECIMAL(17,2) COMMENT 'Accrued Interests SF')
PARTITIONED BY (yyyy STRING, mm STRING, dd STRING, hhmmss STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_de';


CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_fr (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  asset_alternative_account STRING COMMENT 'Asset Alternative Account',
  a5_estimation STRING COMMENT 'A5 Estimation',
  affectation_a5_code STRING COMMENT 'Affectation (A5 code)',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number',
  t2_classification STRING COMMENT 'T2 Classification',
  otc_amortisation_pc DECIMAL(17,2) COMMENT 'OTC Amortisation PC',
  inflation_swap DECIMAL(17,2) COMMENT 'Inflation SWAP�',
  non_liberated_1 DECIMAL(17,2) COMMENT 'Non Liberated',
  non_liberated_2 DECIMAL(17,2) COMMENT 'Non Liberated')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_fr';

CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_fr_all (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  asset_alternative_account STRING COMMENT 'Asset Alternative Account',
  a5_estimation STRING COMMENT 'A5 Estimation',
  affectation_a5_code STRING COMMENT 'Affectation (A5 code)',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number',
  t2_classification STRING COMMENT 'T2 Classification',
  otc_amortisation_pc DECIMAL(17,2) COMMENT 'OTC Amortisation PC',
  inflation_swap DECIMAL(17,2) COMMENT 'Inflation SWAP�',
  non_liberated_1 DECIMAL(17,2) COMMENT 'Non Liberated',
  non_liberated_2 DECIMAL(17,2) COMMENT 'Non Liberated')
PARTITIONED BY (yyyy STRING, mm STRING, dd STRING, hhmmss STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_fr';


CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_w1 (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  sezione STRING COMMENT 'Sezione',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_w1';

CREATE EXTERNAL TABLE IF NOT EXISTS shp_positions_w1_all (
  acquisition_date TIMESTAMP COMMENT 'Acquisition Date',
  actassmtref STRING COMMENT 'ActAssmtRef',
  asset_manager_code STRING COMMENT 'Asset Manager Code',
  business_area STRING COMMENT 'Business area',
  chart_of_accounts STRING COMMENT 'Chart of accounts',
  company_code STRING COMMENT 'Company code',
  contract_type STRING COMMENT 'Contract Type',
  group_of_risk_solv STRING COMMENT 'Group of risk   Solv',
  ifrs_investments_cla STRING COMMENT 'IFRS Investments Cla',
  long_short STRING COMMENT 'Long Short',
  lot STRING COMMENT 'Lot',
  mag_accnt_from_pos_a STRING COMMENT 'Mag Accnt from Pos A',
  magnitude_package STRING COMMENT 'Magnitude Package',
  market_price_date TIMESTAMP COMMENT 'Market Price Date',
  market_price_date_c TIMESTAMP COMMENT 'Market price date 1C',
  market_price_date_2c TIMESTAMP COMMENT 'Market price date 2C',
  original_price_date_1 TIMESTAMP COMMENT 'Original price date',
  original_price_date_2 TIMESTAMP COMMENT 'Original price date',
  original_price_date_3 TIMESTAMP COMMENT 'Original price date',
  position_account STRING COMMENT 'Position Account',
  position_indicator STRING COMMENT 'Position Indicator 1',
  position_indicator_2 STRING COMMENT 'Position Indicator 2',
  position_value_date TIMESTAMP COMMENT 'Position Value Date',
  price_source STRING COMMENT 'Price Source',
  price_source_c STRING COMMENT 'Price Source 1C',
  price_source_2c STRING COMMENT 'Price Source 2C',
  product STRING COMMENT 'Product',
  product_category STRING COMMENT 'Product Category',
  product_company_code STRING COMMENT 'Product Company Code',
  product_type STRING COMMENT 'Product Type',
  segmen STRING COMMENT 'Segmen',
  solv_ii_pos_cl_acc STRING COMMENT 'Solv  II Pos Cl Acc',
  source STRING COMMENT 'Source',
  source_system STRING COMMENT 'Source System',
  valuation_area STRING COMMENT 'Valuation Area',
  valuation_class STRING COMMENT 'Valuation Class',
  calendar_day TIMESTAMP COMMENT 'Calendar day',
  position_currency STRING COMMENT 'Position Currency',
  valuation_currency STRING COMMENT 'Valuation Currency',
  acc_interest_bal_pc DECIMAL(17,2) COMMENT 'Acc Interest Bal PC',
  acc_it_bs_flt_lc DECIMAL(17,2) COMMENT 'Acc It BS FLT LC',
  acc_it_bs_flt_pc DECIMAL(17,2) COMMENT 'Acc It BS FLT PC',
  accrued_intst_bal_lc DECIMAL(17,2) COMMENT 'Accrued Intst Bal LC',
  amort_disc_bal_pc DECIMAL(17,2) COMMENT 'Amort Disc Bal PC',
  amort_disc_bal_lc DECIMAL(17,2) COMMENT 'Amort Disc Bal LC',
  amort_premium_bal_lc DECIMAL(17,2) COMMENT 'Amort Premium Bal LC',
  amort_premium_bal_pc DECIMAL(17,2) COMMENT 'Amort Premium Bal PC',
  amort_accr_def_lc DECIMAL(17,2) COMMENT 'Amort  Accr  Def LC',
  amort_accr_def_pc DECIMAL(17,2) COMMENT 'Amort  Accr  Def PC',
  book_exchange_rate DECIMAL(38,10) COMMENT 'Book Exchange Rate',
  collateral_lc DECIMAL(17,2) COMMENT 'Collateral LC',
  collateral_pc DECIMAL(17,2) COMMENT 'Collateral PC',
  d_cl_pd_def_taxc_pc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC PC',
  d_cl_pd_def_taxc_vc DECIMAL(17,2) COMMENT 'D Cl PD Def  TaxC VC',
  d_impairment_poscrcy DECIMAL(17,2) COMMENT 'D Impairment PosCrcy',
  d_impairment_valcrcy DECIMAL(17,2) COMMENT 'D Impairment ValCrcy',
  d_val_fx_aav_in_vc DECIMAL(17,2) COMMENT 'D Val FX AAV in VC',
  d_swap_mar_a_d_pc DECIMAL(17,2) COMMENT 'D  Swap Mar  A D PC',
  d_vaco_fc_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(FC) NonPL VC',
  d_vaco_sec_nonpl_pc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL PC',
  d_vaco_sec_nonpl_vc DECIMAL(17,2) COMMENT 'D VaCo(Sec) NonPL VC',
  del_fc_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del  FC Val NonPL VC',
  del_amort_acq_val_pc DECIMAL(17,2) COMMENT 'Del Amort Acq Val PC',
  del_amort_acq_val_vc DECIMAL(17,2) COMMENT 'Del Amort Acq Val VC',
  del_bval_ex_costs_pc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs PC',
  del_bval_ex_costs_vc DECIMAL(17,2) COMMENT 'Del BVal Ex Costs VC',
  del_sec_val_nonpl_pc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL PC',
  del_sec_val_nonpl_vc DECIMAL(17,2) COMMENT 'Del Sec Val NonPL VC',
  del_spot_val_purc_vc DECIMAL(17,2) COMMENT 'Del Spot Val PurC VC',
  del_spot_val_salc_vc DECIMAL(17,2) COMMENT 'Del Spot Val SalC VC',
  del_val_fc_costs_vc DECIMAL(17,2) COMMENT 'Del Val  FC Costs VC',
  del_val_se_costs_pc DECIMAL(17,2) COMMENT 'Del Val  SE Costs PC',
  del_val_se_costs_vc DECIMAL(17,2) COMMENT 'Del Val  SE Costs VC',
  delta_accum_repay_pc DECIMAL(17,2) COMMENT 'Delta Accum Repay PC',
  delta_accum_repay_vc DECIMAL(17,2) COMMENT 'Delta Accum Repay VC',
  delta_acq_val_pc DECIMAL(17,2) COMMENT 'Delta Acq Val  PC',
  delta_acq_val_vc DECIMAL(17,2) COMMENT 'Delta Acq Val  VC',
  delta_amort_neg_pc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  PC',
  delta_amort_neg_vc DECIMAL(17,2) COMMENT 'Delta Amort  Neg  VC',
  delta_amortizat_pc DECIMAL(17,2) COMMENT 'Delta Amortizat  PC',
  delta_amortizat_vc DECIMAL(17,2) COMMENT 'Delta Amortizat  VC',
  delta_book_val_pc DECIMAL(17,2) COMMENT 'Delta Book Val  PC',
  delta_book_val_vc DECIMAL(17,2) COMMENT 'Delta Book Val  VC',
  delta_costs_pc DECIMAL(17,2) COMMENT 'Delta Costs PC',
  delta_costs_vc DECIMAL(17,2) COMMENT 'Delta Costs VC',
  delta_fc_val_vc DECIMAL(17,2) COMMENT 'Delta FC Val  VC',
  delta_fx_impairmt_vc DECIMAL(17,2) COMMENT 'Delta FX Impairmt VC',
  delta_no_of_units DECIMAL(17,3) COMMENT 'Delta No  of Units',
  delta_nom_amnt_pc DECIMAL(17,2) COMMENT 'Delta Nom  Amnt PC',
  delta_purch_amnt_pc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt PC',
  delta_purch_amnt_vc DECIMAL(17,2) COMMENT 'Delta Purch  Amnt VC',
  delta_sec_val_pc DECIMAL(17,2) COMMENT 'Delta Sec Val  PC',
  delta_sec_val_vc DECIMAL(17,2) COMMENT 'Delta Sec Val  VC',
  delta_swap_val_vc DECIMAL(17,2) COMMENT 'Delta Swap Val  VC',
  delta_swapmar_a_d_vc DECIMAL(17,2) COMMENT 'Delta SwapMar A D VC',
  delta_var_margin_pc DECIMAL(17,2) COMMENT 'Delta Var Margin PC',
  delta_var_margin_vc DECIMAL(17,2) COMMENT 'Delta Var Margin VC',
  eff_int_rate_pos DECIMAL(38,10) COMMENT 'Eff  Int  Rate (pos)',
  exchange_rate DECIMAL(38,10) COMMENT 'Exchange Rate',
  index_linked_bond_am DECIMAL(17,2) COMMENT 'Index Linked Bond Am',
  ix_lk_bd_am_ng_bl_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Am Ng Bl PC',
  ix_lk_bd_amnprbal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd AmNPrBal LC',
  ix_lk_bd_valg_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal LC',
  ix_lk_bd_valg_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValG Bal PC',
  ix_lk_bd_vall_bal_lc DECIMAL(17,2) COMMENT 'Ix Lk Bd ValL Bal LC',
  ix_lk_bd_vals_bal_pc DECIMAL(17,2) COMMENT 'Ix Lk Bd Vals Bal PC',
  ix_lk_bdampsdc_ballc DECIMAL(17,2) COMMENT 'Ix Lk BdAmPsDc BalLC',
  market_price_c_pc DECIMAL(38,10) COMMENT 'Market Price 1C PC',
  market_price_c_vc DECIMAL(38,10) COMMENT 'Market Price 1C VC',
  market_price_2c_pc DECIMAL(38,10) COMMENT 'Market Price 2C PC',
  market_price_2c_vc DECIMAL(38,10) COMMENT 'Market Price 2C VC',
  market_price_pc DECIMAL(38,10) COMMENT 'Market Price PC',
  market_price_vc DECIMAL(38,10) COMMENT 'Market Price VC',
  market_value_c_pc DECIMAL(17,2) COMMENT 'Market Value 1C PC',
  market_value_c_vc DECIMAL(17,2) COMMENT 'Market Value 1C VC',
  market_value_2c_pc DECIMAL(17,2) COMMENT 'Market Value 2C PC',
  market_value_2c_vc DECIMAL(17,2) COMMENT 'Market Value 2C VC',
  market_value_pc DECIMAL(17,2) COMMENT 'Market Value PC',
  market_value_vc DECIMAL(17,2) COMMENT 'Market Value VC',
  nom_am_total_harm DECIMAL(17,2) COMMENT 'Nom Am Total Harm',
  nom_tot_harm_bal_lc DECIMAL(17,2) COMMENT 'Nom  Tot Harm Bal LC',
  nominal_am_harmzd DECIMAL(17,2) COMMENT 'Nominal Am Harmzd',
  nominal_harm_bal_lc DECIMAL(17,2) COMMENT 'Nominal Harm  Bal LC',
  nominal_lc DECIMAL(17,2) COMMENT 'Nominal LC',
  otc_amortisation_lc DECIMAL(17,2) COMMENT 'OTC Amortisation LC',
  record_count BIGINT COMMENT 'Record Count',
  units_harmonized DECIMAL(17,3) COMMENT 'Units Harmonized',
  sezione STRING COMMENT 'Sezione',
  lot_generating_transaction_number STRING COMMENT 'Lot-Generating Transaction Number')
PARTITIONED BY (yyyy STRING, mm STRING, dd STRING, hhmmss STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/group/pisquare/data/shp_positions_w1';


